import React from "react";
import Navbar from "components/Navbars/IndexNavbar.js";
import Footer from "components/Footers/FooterAdmin.js";

export default function TandC() {
    return (
        <>
            <Navbar transparent />
            <main>
                <div className="container mx-auto px-4">
                    <div className="flex flex-wrap justify-center text-center mt-20">
                        <div className="w-full lg:w-8/12 px-4">
                            <h2 className="text-4xl font-semibold">Terms of Use</h2>
                        </div>
                    </div>
                    <div className="flex flex-wrap justify-center mt-10">
                        <div className="w-full lg:w-8/12 px-4">
                            <p>
                                By accessing and using the azoapp.tech website and/or our Services as defined below, you confirm that you are in agreement with and bound by the terms of use given here.
                            </p>
                            <br />
                            <p>
                                <strong>1. ACCEPTANCE OF TERMS</strong>
                            </p>
                            <br />
                            <p>
                                Azo having its office at D-10/6, First Floor, Ardee City, Gurugram 122003, Haryana, India (HEREINAFTER REFERRED TO AS “Azo (hereinafter referred to as “Azo”/ “Azo App”/ “WE”/ “US”/ “OUR”), ON BEHALF OF ITSELF AND ITS AFFILIATES/GROUP COMPANIES UNDER THE BRAND ‘Azo’, OPERATES THE WEBSITE ‘www.azoapp.tech’ and all its subdomains and webpages (TOGETHER REFERRED TO AS “PLATFORM”).
                            </p>
                            <br />
                            <p>
                                THIS DOCUMENT IS A LEGALLY BINDING DOCUMENT WHETHER YOU ARE A REGISTERED OR UNREGISTERED USER OF THE PLATFORM (HEREINAFTER REFERRED TO AS “YOU”/ “YOUR”/ “USER”) AND IS A BINDING AGREEMENT BETWEEN THE USER AND US IN RELATION TO THE USE OF THE PLATFORM AND SETS FORTH THE TERMS AND CONDITIONS BY WHICH YOU MAY ACCESS AND USE THE PLATFORM, SERVICES AVAILABLE ON THE PLATFORM, ADD-ON SERVICES AND OUR RELATED WEBSITES, SERVICES, APPLICATIONS, PRODUCTS AND CONTENT (COLLECTIVELY, THE “SERVICES”).
                            </p>
                            <br />
                            <p>
                                THE TERMS OF THIS DOCUMENT WILL BE EFFECTIVE UPON YOUR ACCEPTANCE OF THE SAME (DIRECTLY OR INDIRECTLY IN ELECTRONIC FORM, OR BY CONTINUING USE OF THE PLATFORM AND/OR BY CREATING A REGISTERED ACCOUNT ON THE PLATFORM (HEREINAFTER REFERRED TO AS “ACCOUNT”) AND WILL GOVERN THE RELATIONSHIP BETWEEN YOU AND US FOR YOUR USE OF THE PLATFORM AND THE SERVICES RENDERED THEREIN.
                            </p>
                            <br />
                            <p>
                                THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE RELEVANT APPLICABLE LAWS. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
                            </p>
                            <br />
                            <p>
                                THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE RELEVANT APPLICABLE LAWS THAT REQUIRE PUBLISHING INTER ALIA THE TERMS OF USE, AND PRIVACY POLICY FOR ACCESS OR USAGE OF THE PLATFORM AND THE SERVICES RENDERED THEREUNDER.
                            </p>
                            <br />
                            <p>
                                PLEASE READ THIS DOCUMENT CAREFULLY. BY USING THE PLATFORM, YOU INDICATE THAT YOU UNDERSTAND, AGREE AND CONSENT TO THIS DOCUMENT. IF YOU DO NOT AGREE WITH THE TERMS OF THIS DOCUMENT, PLEASE DO NOT USE THIS PLATFORM AND SERVICES. YOU HEREBY PROVIDE YOUR UNCONDITIONAL CONSENT OR AGREEMENT TO US AS PROVIDED UNDER THE RELEVANT APPLICABLE LAWS TO ACCESS AND USE YOUR PERSONAL INFORMATION THAT YOU HAVE VOLUNTARILY PROVIDED TO US IN CONNECTION WITH THE USE OF THE PLATFORM AND THE SERVICES.
                            </p>
                            <br />
                            <p>
                                By providing Us Your information or by making use of the Platform and the Services provided therein, You hereby consent to the collection, storage, processing, and transfer of any or all Personal Information (defined in Our Privacy Policy) and Non-Personal Information by Us as specified under this Terms of Use and further agree that such collection, use, storage, and transfer of information shall not cause any loss or wrongful gain to You or any other person.
                            </p>
                            <br />
                            <p>
                                You must be at least eighteen (18) years or older to access and use this Platform. A minor (i.e., below the age of 18 years) shall not be entitled to avail the Services of this Platform. Your entity or organization on behalf of which You are accessing the Platform and availing the Services should have been incorporated as per the applicable laws.
                            </p>
                            <br />
                            <p>
                                If You are using the Services as an employee, agent, or contractor of a corporation, partnership or similar entity, then You represent and warrant that You have the authority to sign for and bind such entity in order to accept this Terms of Use.
                            </p>
                            <br />
                            <p>
                                Your access to the Platform and use of Our Services is also subject to Our Privacy Policy, the terms in the privacy policy can be found directly on the Platform and are incorporated herein by reference. You agree that all agreements, notices, disclosures, and other communications We provide to You electronically satisfy any legal requirement that such communications be in writing.
                            </p>
                            <br />
                            <p>
                                Before You use or subscribe to, and/or begin participating in or using the Platform, it is represented and warranted that You as the User of the Platform have fully read, understood, and accept the Terms of Use as updated from time to time without any notice to You. You are advised to review this Terms of Use periodically for any updates. We shall take reasonable efforts to notify You regarding the amendments to the Terms of Use through a notice on the Platform. Your continued access to the Platform and/or use of the Services from the date of updated Terms of Use shall be deemed to Your acceptance of the updated Terms of Use. If You do not agree to or wish to be bound by the updated Terms of Use, You may not access or otherwise use the Platform or Services.
                            </p>
                            <br />
                            <p>
                                We may, from time to time, release new versions of the Platform, or release/introduce new and additional scope of Services which will be subject to these Terms of Use, and any additional terms of Service as may apply to such additional new version or Services.
                            </p>
                            <br />
                            <p>
                                <strong>2. SERVICES</strong>
                            </p>
                            <br />
                            <p>
                                Through the Platform, We shall provide automated digital marketing services to You, or any other services specified under the relevant service agreement or order form that may be entered in this regard, or any new services that We may introduce from time to time as a Service to which You may subscribe to, and any updates, modifications, or improvements thereto (“collectively referred to as Services”).
                            </p>
                            <br />
                            <p>
                                If You wish to subscribe to Our subscription plan and avail Services or any other Services available on the Platform, You shall agree and execute the Master End-User License and Subscription Services Agreement (“Agreement”) which can be found directly on the Platform and shall also be made available upon Your request.
                            </p>
                            <br />
                            <p>
                                <strong>Add-on Services</strong>
                            </p>
                            <br />
                            <p>
                                The Platform shall be pre-integrated with a number of third-party add-on services. These add-on services are provided by third-party vendors. When You purchase such services through the Platform, the terms and conditions of those third-party vendors may apply to You. You are urged to review such terms and conditions before purchasing or otherwise accessing any such add-on services through the Platform. We cannot and do not take any responsibility for, nor make any warrant on behalf of, such add-on services or responsible for the terms and conditions set forth by such third-party vendors.
                            </p>
                            <br />
                            <p>
                                Any exchange of data or information between You and the third-party add-on services’ vendors is solely between You and the third-party add-on services’ vendors, and We are not responsible for any disclosure, modification, or deletion of the User data (defined below) resulting from access by such third-party add-on services’ vendor.
                            </p>
                            <br />
                            <p>
                                For the purpose of clarification, “User Data” shall mean all electronic data, text, messages, User Content, logo, or other materials, including without limitation to Personal Data of the User, and its end-users (if any), submitted by You to Us in connection with the use of the Services.
                            </p>
                            <br />
                            <p>
                                <strong>Third-Party Platform Integration</strong>
                            </p>
                            <br />
                            <p>
                                We shall integrate with certain third-party platforms to render Our Services to You. Therefore, if You avail any Services which requires integration with third-party platforms, then, You shall be bound by the terms and conditions of such third-party platforms. Further, if You suffer any loss or damage or injury in relation to the third-party platforms, You acknowledge that We shall not be liable for the loss or damage or injury and You agree that You shall make claim against such third-party platforms for the loss or damage or injury suffered by You.
                            </p>
                            <br />
                            <p>
                                <strong>Creation and Publication of Advertisement</strong>
                            </p>
                            <br />
                            <p>
                                In order to publish advertisement on multiple social media platforms through the Platform, You may either submit the advertisement content (“Advertisement”) or engage Our advertisement and content creators for creating Advertisement for your purpose. You shall promptly check any proofs of advertising provided by such creators and notify Us with any changes or any errors in the proofs or in any Advertisement that We publish for You. We do not accept any responsibility for errors in advertising material that has been submitted electronically by You. We shall not publish any Advertisement on your behalf that has not been submitted by you electronically on our platform for publishing, without your prior written approval.
                            </p>
                            <br />
                            <p>
                                We will, subject to availability, technical limitations, and this Terms of Use, use Our reasonable endeavors to publish Your Advertisement in the pre-approved format submitted by You and in accordance with Your other instructions. However, We will not be liable for any costs, expenses, losses or damages suffered or incurred by You arising from our failure to publish Your Advertisement in accordance with Your request.
                            </p>
                            <br />
                            <p>
                                You acknowledge that We are entitled to publish Your Advertisement via the social media platform authorized by You. We may refuse to publish any Advertisement provided by You without giving any reason, at Our sole discretion. We reserve the right to refuse or withdraw Your Advertisement from publication at any time, without giving reasons, even if We have previously published the same or similar advertisement and even if there is contract that has been formed between Us.
                            </p>
                            <br />
                            <p>
                                We may, with prior consultation or notice to You, amend Your Advertisement, if We believe that the publication of Your Advertisement would be offensive, in breach of any law, in breach of any pre-existing agreement we have with a third party or in breach of a third-party rights. Any amendment to Your Advertisement shall not reduce the Subscription Fee agreed between Us.
                            </p>
                            <br />
                            <p>
                                By submitting advertising material to Us or authorizing or approving the publication of Advertisement by Us on Your behalf, You warrant that the Advertisement complies with all relevant laws and regulations and that its publication will not give rise to any claims or liabilities against Us, our partners, Our directors, employees or agents. By submitting, authorizing or approving Advertisement for publication by Us, You indemnify Us and Our partners, our directors, employees and agents against all claims, demands, proceedings and other liability arising wholly or partially, directly or indirectly, from the publication of the Advertisement and from any negligent or unlawful act or omission by You in connection with the publication of Advertisement.
                            </p>
                            <br />
                            <p>
                                Azo shall not be held responsible for the inherent quality of leads generated through digital advertising campaigns conducted on third-party platforms. Our primary function is to facilitate and automate digital marketing campaigns on various online platforms, including but not limited to Facebook and Google. While the Platform provides tools and capabilities to optimize ad targeting and audience segmentation, it does not have control over the quality of leads inherently generated through these third-party advertising channels.
                            </p>
                            <br />
                            <p>
                                The Platform does not make any warranties or guarantees, either expressed or implied, regarding the quality, relevance, or conversion potential of leads generated through digital advertising campaigns. Lead quality may vary based on various factors including ad creative, targeting parameters, market dynamics, and user engagement, which are beyond the Platform's control.
                            </p>
                            <br />
                            <p>
                                Any issues related to lead quality, ad performance, or compliance with platform policies should be addressed directly with the respective advertising platforms. The Platform may provide data analytics and reporting features to help users assess the performance of their digital marketing campaigns. However, these analytics are based on data provided by third-party platforms and should be used for informational purposes only. The Platform shall not be held liable for any decisions made based on these analytics.
                            </p>
                            <br />
                            <p>
                                Users of the Platform are encouraged to employ best practices, conduct A/B testing, and continually optimize their advertising strategies to improve lead quality and overall campaign performance.
                            </p>
                            <br/>
                            <p>
                                <strong>3. BETA SERVICES</strong>
                            </p>
                            <br/>
                            <p>
                                We make available to You, some or all portions of the Website and the Platform that are in the beta development, and evaluation phase currently (“Azo Beta Services”). It is hereby clarified that the Azo Beta Services may contain bugs, errors, omissions, and other problems. You hereby understand and accept that any risk or damages arising out of the use or performance of the Azo Beta Services will be Your responsibility.
                            </p>
                            <p>
                                The Azo Beta Services may be substantially modified prior to their first commercial availability or may be withdrawn at any time. Although We will make best possible efforts to intimate users of Azo Beta Services about any modification or termination of such Services ahead of time, We reserve the right to modify or terminate the Azo Beta Services and Your access to the Azo Beta Services for any reason, without notice, at any time, and without any liability to Us.
                            </p>
                            <p>
                                You may follow the procedure mentioned below in Clause 4 for signing up with Us for availing Our other Services on the Platform.
                            </p>
                            <br/>
                            <p>
                                <strong>4. SIGNING UP AND ACCOUNT REGISTRATION</strong>
                            </p>
                            <br/>
                            <p>
                                <strong>Procedure for signing up:</strong>
                            </p>
                            <br/>
                            <p>
                                In case You are desirous of availing Our Services, You are required to sign up for Our Services by following the below given steps:
                            </p>
                            <p>
                                You shall reach Us through Our Website <a href="https://www.azoapp.tech">https://www.azoapp.tech</a> and complete the Signup form(s) (“Form”) available on the Website. By filing up the Form, You provide Us with certain information in relation to You or Your business, including but not limited to:
                            </p>
                            <ul>
                                <li>Your name</li>
                                <li>Your company/entity’s name</li>
                                <li>Your designation in the company/entity</li>
                                <li>Your email address</li>
                                <li>Your phone number</li>
                            </ul>
                            <p>
                                You can choose not to fill up the form or provide such information sought by Us, and in such cases, You may not be able to sign up for Our Services. Whereas, if You have filled up the Form or provided Us with the information sought by Us, We shall contact you either through the email address or phone number given by You.
                            </p>
                            <p>
                                Further, You shall be provided with a product demo on request for You to determine whether to avail Our Services. We shall reserve the right to provide another set of demos to You for better understanding of Our Services. After such demo(s) of the Platform and if You wish to sign up for Our Services, You are required to complete the signup and create an Account to avail Our Services.
                            </p>
                            <br/>
                            <p>
                                <strong>Account Registration:</strong>
                            </p>
                            <br/>
                            <p>
                                To use Our Services on the Platform, You will need to create an Account on the Platform and become a registered Account holder of the Platform by registering in the manner as fully specified under the Agreement. Further, other terms in relation to maintenance of an Account shall be stipulated under the Agreement. Thereby, You are also bound by terms of the Agreement and Order Form if You are availing Our Services available on the Platform.
                            </p>
                            <br/>

                            <p>
                                <strong>5. SUBSCRIPTION PLAN</strong>
                            </p>
                            <br/>
                            <p>
                                The User, to avail Our Services shall choose an appropriate subscription plan mutually agreed between You and Us from time-to-time basis, and You agree to pay the applicable fee in advance on yearly, quarterly, monthly basis, unless otherwise agreed in the Agreement/Order Form (“Subscription Fee”). Further, the payment terms and other terms in relation to the Subscription Fee shall be specified in detail under the Agreement or in the relevant Order form.
                            </p>
                            <br/>

                            <p>
                                <strong>6. PLATFORM ACCESS AND USE OF SERVICES</strong>
                            </p>
                            <br/>
                            <p>
                                You shall not use the Platform or the Services therein to host, display, upload, modify, publish, transmit, store, update or share any information that:
                            </p>
                            <br/>
                            <ul>
                                <li>belongs to another person and to which You do not have any right.</li>
                                <li>is defamatory, obscene, pornographic, pedophilic, invasive of any third-party’s privacy, including bodily privacy, insulting, or harassing on the basis of gender, libelous, racially, or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force.</li>
                                <li>is harmful to a child.</li>
                                <li>infringes any patent, trademark, copyright, or other proprietary rights.</li>
                                <li>violates any law for the time being in force.</li>
                                <li>deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact.</li>
                                <li>impersonates another person.</li>
                                <li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting other nation.</li>
                                <li>contains software virus or any other computer code, file or program designed to interrupt, destroy, or limit the functionality of any computer resource.</li>
                                <li>is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity, or agency for financial gain or to cause any injury to any person.</li>
                                <li>any unlawful information, which is prohibited under any law for the time being in force in relation to the interest of the sovereignty and integrity of India; security of the State; friendly relations with foreign States; public order; decency or morality; in relation to contempt of court; defamation; incitement to an offence relating to the above, or any information which is prohibited under any law for the time being in force.</li>
                                <li>any private information of any third party, including addresses, phone numbers, email addresses or any personal identifiable information.</li>
                            </ul>
                            <br/>
                            <p>
                                You agree to not use the Platform to:
                            </p>
                            <br/>
                            <ul>
                                <li>upload, post, email or otherwise make available or transmit any material that contains software viruses, or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
                                <li>disrupt the normal flow of dialogue, cause a screen to “scroll” faster than other Users of the Service are able to type, or otherwise act in a manner that negatively affects other Users’ ability to engage in real time exchanges or to utilize the service on an as is basis as provided by Us;</li>
                                <li>interfere with or disrupt the Platform or servers or networks connected to the Platform, or disobey any requirements, procedures, policies or regulations of networks connected to the Platform;</li>
                                <li>intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the Indian securities, exchange control and other regulatory authorities, any rules of any Indian securities exchange and any regulations having the force of law;</li>
                                <li>commit any fraudulent or unlawful act, whether in relation to any third-party provider of products and services on the Service or otherwise;</li>
                                <li>make unauthorized copies, modify, adapt, translate, reverse engineer, disassemble, decompile or create any derivative works of the Services or any content included therein, including any files, tables or documentation (or any portion thereof) or determine or attempt to determine any source code, algorithms, methods or techniques embodied by the Services or any derivative works thereof;</li>
                                <li>distribute, license, transfer, or sell, in whole or in part, any of the Services or any derivative works thereof;</li>
                                <li>market, rent or lease the Services for a fee or charge;</li>
                                <li>use the Services, without our express written consent, for any unauthorized purpose, including solicitation or spamming;</li>
                                <li>incorporate the Services or any portion thereof into any other program or product. In such case, we shall have the right to terminate the Service and Your accounts or limit access to the Services, as the case may be, in our sole discretion;</li>
                                <li>impersonate, or falsely state or otherwise misrepresent Your affiliation with any person;</li>
                                <li>infringes any patent, trademark, trade secret, copyright or other proprietary rights (“Rights”) of any party;</li>
                                <li>use or attempt to another user’s account, service, or system, or create a false identity on the Services.</li>
                            </ul>
                            <br/>
                            <p>
                                In addition to the above, You shall also be compliant to Our Privacy Policies as updated from time to time, a copy of which is available on our Platform.
                            </p>
                            <br/>
                            <p>
                                You are solely responsible for all information You transmit or share through the Platform. In the event of non-compliance of this Terms of Use, We may (without notice to You), immediately terminate Your registration with Us and/or prevent Your access of the Platform and Services thereunder.
                            </p>
                            <br/>
                            <p>
                                You acknowledge that the Platform may contain third-party content or hyperlinks to third-party websites or services displayed in the Platform that are not owned or controlled by Us. They are provided as an information service, for reference and convenience only. We do not control any such third-party content and is not responsible for their availability or accuracy content, advertising, or products or services and the inclusion of such third-party content does not constitute or indicate any kind endorsement of endorsement by Us. We shall not be liable or responsible for any such third-party content transmitted through the Platform. Such third-party content shall not be monitored, censored, or edited by Us, and we assume no liability or responsibility for any of your action in relation to such third-party content. You shall read and understand the privacy policy and terms of use associated with such third-party content before using the same.
                            </p>
                            <br/>
                            <p>
                                By using the Platform, You expressly relieve and hold Us harmless from any and all liability arising from Your use of any third-party communications and third-party content, including any loss or damage incurred as a result of any dealings between You and any third parties, or as the result of the presence of such third-party content on the Platform or the failure of such third-party content to function as intended. It is Your responsibility to evaluate the content and usefulness of the information obtained from third-party content.
                            </p>
                            <br/>
                            <p>
                                <strong>7. PERSONAL DATA PROTECTION</strong>
                            </p>
                            <br/>
                            <p>
                                Our obligation for the use of Personal Data (defined in Our Privacy Policy) will be restricted within the scope of the purpose of collecting and processing such Personal Data, subject to Our Privacy Policies.
                            </p>
                            <br/>
                            <p>
                                <strong>Personal Data.</strong> Subject to this Terms of Use, to the extent that We receive certain Personal Data as a result of rendering Our Services, We agree that we will
                            </p>
                            <br/>
                            <ul>
                                <li>not disclose or use any of Your Personal Data except to the extent necessary to carry out Our obligations hereinunder and for no other purpose,</li>
                                <li>not disclose Your Personal Data to any third party, other than Our third party service providers for purposes as defined in our Privacy Policy or and subject to the further requirements of this clause,</li>
                                <li>employ administrative, technical and physical safeguards to prevent unauthorized use or disclosure of Your Personal Data,</li>
                                <li>promptly provide such information regarding its privacy and information security systems, policies and procedures as You may request relating to its due diligence and oversight obligations under applicable laws and regulations,</li>
                                <li>in the event of any actual or apparent theft, unauthorized use or disclosure of any of Your Personal Data immediately commence all reasonable efforts to investigate and correct the causes and remediate the results thereof, and</li>
                                <li>as soon as practicable following discovery of any event described in sub-clause (e) hereof, provide You a notice thereof, and such further information and assistance as may be reasonably requested. We shall reasonably assist You, at Your expense, in meeting Your obligations under applicable data protection laws.</li>
                            </ul>
                            <br/>

                            <p>
                                <strong>8. INTELLECTUAL PROPERTY RIGHTS AND PLATFORM LICENSE</strong>
                            </p>
                            <br/>
                            <p>
                                The copyright, database right and other intellectual property rights in the Platform, products and Services including without limitation all content included on the Platform including but not limited to Registration Data, texts, graphics, logos, button icons, images, audios, clips, digital downloads, software, data compilations and technology used or appearing or transmitted through it (“Azo’s Intellectual Property”), belongs to Us or Our affiliates or licensors and are protected by the laws of India, other countries and international treaties and regulations. We and Our licensors reserve all rights not expressly granted in these Terms of Use.
                            </p>
                            <br/>
                            <p>
                                All software used on the Platform is Azo’s Intellectual Property and is protected by Indian and international copyright laws.
                            </p>
                            <br/>
                            <p>
                                Subject to this Terms of Use and solely within the limits permitted by Us herein, We grant You a limited, non-exclusive, revocable, royalty-free, non-transferable, non-assignable, non-sublicensable, right and license to access and make personal use of the Platform, the Services provided in the Platform. This license does not include any redistribution of resale or commercial use of the Platform.
                            </p>
                            <br/>
                            <p>
                                You shall not re-utilise the Services of Our Platform or systematically extract any part of the content, use any robots, data mining or extraction tools for reutilization of Our Platform. Further, You shall not create publish anything that features parts of Our Platform (for example Our Services and its prices) without our prior written permission.
                            </p>
                            <br/>
                            <p>
                                “Azo”, Our logo, and local language variants of the foregoing trademarks, and certain product names that appear on this Platform, are trademarks or registered trademarks of Azo. Except as expressly provided in these Terms of Use or as expressly authorized in writing by the Us, You shall not use any Azo’s Intellectual Property either alone or in combination with other words or design elements, including, in any press release, advertisement, or other promotional or marketing material or media, whether in written, oral, electronic, visual, or any other form.
                            </p>
                            <br/>
                            <p>
                                You own the rights to User Data that You provide to Us. We do not claim ownership over such User Data. We shall have a right and license to incorporate the User Data into the Services or otherwise use any suggestions, enhancement requests, recommendations or other feedback received from You. We reserve Our rights to re-use any and all techniques and know-how gathered by Us while providing the Services to You. All rights not expressly provided to You herein are reserved.
                            </p>
                            <br/>
                            <p>
                                By using our services and accepting these terms of use, You grant Us royalty-free, nonexclusive, nontransferable, and non-assignable license and permission to use Your name, business name and logo for our marketing or promotional purposes. If you wish to revoke this license & permission to use of your name, business name and logo for our marketing & promotional purposes, you must stop use of our services immediately and inform us by email at support@azoapp.tech and we will remove any references of your name or logo from our marketing materials within a reasonable timeframe, not exceeding 30 days from such notice.
                            </p>
                            <br/>
                            <p>
                                References to other parties’ trademarks on this Platform including but not limited to Our payment service providers and other service providers are for identification purposes only and do not indicate that such parties have approved this Platform or any of its Services. These Terms of Use do not grant You any right to use the trademarks of such other third parties.
                            </p>
                            <br/>
                            <p>
                                <strong>9. USER CONTENT</strong>
                            </p>
                            <br/>
                            <p>
                                You will retain all right, title and interest (including any and all intellectual property rights) that You may have in and to the data, including but not limited to all text, sound, video, or image files (collectively the “User Content”), as submitted by You to enable us to render Services to You including but not limited to creation and publication of Advertisements. You represent and warrant to Us that the User Content will not violate or infringe (i) any third party intellectual property, publicity, privacy or other rights or (ii) any applicable laws. Subject to the terms of this Terms of Use, You hereby grant Us a non-exclusive, worldwide, royalty-free license to use, store, transmit, transfer, modify, create derivative works of and display the User Content solely to the extent necessary to provide the Services to You.
                            </p>
                            <br/>
                            <p>
                                We do not pre-screen the User Content submitted/uploaded by You on the Platform for the purpose of availing Our Services. However, We have the right to, in Our sole discretion, to refuse or remove the User Content that is provided by You on the Platform.
                            </p>
                            <br/>
                            <p>
                                <strong>10. REPRESENTATIONS AND WARRANTIES</strong>
                            </p>
                            <br/>
                            <p>
                                You represent and warrant that:
                            </p>
                            <br/>
                            <ul>
                                <li>You are fully capable and competent to enter into this Terms of Use and that You have the right, authority, and capacity to enter into, and to be bound by, this Terms of Use and to abide by the terms and conditions contained herein, and that You will so abide.</li>
                                <li>You shall not avail any of the Services beyond the contemplated functionality of the Services.</li>
                                <li>You shall not attempt to gain unauthorized access to any of the Services or any networks, servers or computer systems connected to the Services.</li>
                                <li>You shall not avail any of the Services in a way that may damage or impair (i) the Services, or (ii) Our underlying systems and security.</li>
                                <li>You shall not avail any of the Services in any unlawful manner, or in a manner which promotes or encourages illegal activity, including (without limitation) copyright infringement or data theft.</li>
                                <li>You shall not use any intellectual property whether owned by Us or other third parties, including the copyrighted content displayed on the Platform for any personal or third-party gain, without Our express consent.</li>
                                <li>You agree to promptly notify and bring to Our notice in the event Your Mobile Contact Number is in the Do Not Disturb/National Consumer Preference Register List of the Telecom Regulatory Authority of India (“TRAI”) or similar regulatory body in your country, immediately after the Primary Registration.</li>
                                <li>You shall not modify, adapt, translate, or reverse engineer any part of the Services (e.g., by creating a shadow site or Website that mirrors the said Services, or substantially mirrors said Services).</li>
                                <li>You agree that We or our agents may contact You at the telephone number You provide to us. You agree to receive these calls and messages, such as a text message or prerecorded or autodialed calls. You understand that Your service provider may charge You for these calls/messages. You understand and acknowledge that any calls, text messages that You receive from Us on Your Mobile Contact Number are not unsolicited calls or messages.</li>
                                <li>You will not carry out any action or omit to do any action which will create liability for Us or cause Us to lose (in whole or in part) the Services of Our Internet service providers (ISPs) or other partners, suppliers, contractors, vendors.</li>
                            </ul>
                            <br/>
                            <p>
                                <strong>11. CONFIDENTIALITY</strong>
                            </p>
                            <br/>
                            <p>
                                Each party acknowledges and agrees that in the performance of this Terms of Use it may have access to or may be exposed to, directly or indirectly, Confidential Information (defined under the Agreement) of the other party.
                            </p>
                            <br/>
                            <p>
                                Each party acknowledges and agrees that: (a) all Confidential Information shall remain the exclusive property of the disclosing Party; (b) it shall not use Confidential Information of the other party for any purpose except in furtherance of this Terms of Use; (c) it shall not disclose Confidential Information of the other party to any third party, except to its employees, officers, contractors, agents and service providers on a need to know basis in connection with the Terms of Use, provided such permitted persons are bound in writing to obligations of confidentiality and non-use of Confidential Information no less protective than the terms hereof; and (d) it shall return or destroy all Confidential Information of the disclosing party upon the termination of the Terms of Use or at the request of the disclosing party (subject to applicable law and, with respect to Us and Our internal record-keeping requirements).
                            </p>
                            <br/>
                            <p>
                                Notwithstanding the foregoing, Confidential Information shall not include any information to the extent it: (a) is or becomes part of the public domain through no act or omission on the part of the receiving party; (b) was possessed by the receiving party prior to the date of signing up on the Account without an obligation of confidentiality; (c) is disclosed to the receiving party by a third party having no obligation of confidentiality with respect thereto; or (d) is required to be disclosed pursuant to applicable law, court order, subpoena or governmental authority, provided the receiving party notifies the disclosing party thereof and provides the disclosing party a reasonable opportunity to contest or limit such required disclosure.
                            </p>
                            <br/>
                            <p>
                                <strong>12. DISCLAIMER OF WARRANTIES</strong>
                            </p>
                            <br/>
                            <p>
                                YOUR USE OF THE PLATFORM AND OUR SERVICES IS ENTIRELY AT YOUR OWN RISK. TO THE EXTENT NOT OTHERWISE SET IN THIS TERMS OF USE AND TO THE FULLEST EXTENT PERMITTED UNDER LAW, THE PLATFORM IS PROVIDED ON AN “AS IS” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF (A) MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY, CURRENTESS, COMPLETENESS OR RELIABILITY OF ANY SERVICES PROVIDED THROUGH THE PLATFORM OR THIRD PARTY SERVICES LINKED TO THE PLATFORM AND ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY ERRORS, MISTAKES, OR INACCURACIES OF SERVICE, (B) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE PLATFORM, (C) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN (D) YOUR USE OF THE SERVICES WILL MEET YOUR REQUIREMENTS (E) ANY INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE AND DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO YOU AS PART OF THE SERVICES WILL BE CORRECTED.
                            </p>
                            <br/>
                            <p>
                                WE DO NOT WARRANT, ENDORSE, GUARANTEE OR ASSUME RESPONSIBILITY FOR ANY SERVICE OFFERED BY A THIRD PARTY THROUGH THE PLATFORM OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY BANNER AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES, OTHER THAN AS PROVIDED HEREIN. AS WITH THE AVAILING OF ANY SERVICES THROUGH SUCH THIRD-PARTY LINKS, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.
                            </p>
                            <br/>
                            <p>
                                WITHOUT LIMITING THE FOREGOING, NEITHER US NOR OUR AFFILIATES OR LICENSORS WARRANT THAT ACCESS TO THE PLATFORM WILL BE UNINTERRUPTED OR THAT THE PLATFORM WILL BE ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED OR THAT IT WILL ALWAYS BE ACCESSIBLE; NOR WE MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE PLATFORM, OR AS TO THE TIMELINESS, ACCURACY, RELIABILITY, COMPLETENESS OR, INFORMATION OR MATERIALS OR SERVICES PROVIDED THROUGH OR IN CONNECTION WITH THE USE OF THE PLATFORM. NEITHER US NOR OUR AFFILIATES OR LICENSORS IS RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER. WE, OUR AFFILIATES AND LICENSORS DO NOT WARRANT THAT THE PLATFORM IS FREE FROM VIRUSES, WORMS, TROJAN HORSES, OR OTHER HARMFUL COMPONENTS AND DO NOT GUARANTEE THAT ANY PERSONAL INFORMATION SUPPLIED BY YOU WILL NOT BE MISAPPROPRIATED, INTERCEPTED, DELETED, DESTROYED OR USED BY OTHERS.WE MAY CHANGE, SUSPEND, WITHDRAW OR RESTRICT THE AVAILABILITY OF ALL OR ANY PART OF OUR PLATFORM FOR BUSINESS AND OPERATIONAL REASONS AT ANY TIME WITHOUT NOTICE.
                            </p>
                            <br/>
                            <p>
                                <strong>13. LIMITATION OF LIABILITY</strong>
                            </p>
                            <br/>
                            <p>
                                UNDER NO CIRCUMSTANCES WILL WE, OUR AFFILIATES, LICENSORS, OR ANY OF SUCH PARTIES’ AGENTS, EMPLOYEES, OFFICERS, DIRECTORS, CORPORATE PARTNERS, OR PARTICIPANTS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR EXEMPLARY DAMAGES ARISING IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE PLATFORM, EVEN IF ADVISED OF THE POSSIBILITY OF THE SAME INCLUDING BUT NOT LIMITED TO ANY LOSS OF PROFIT (WHETHER INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS OF GOODWILL(C), ANY LOSS OF OPPORTUNITY, ANY LOSS OF DATA SUFFERED BY YOU.
                            </p>
                            <br/>
                            <p>
                                WITH RESPECT TO THE SUBSCRIBED SERVICES, THE RESPECTIVE CLAUSE ON THE LIMITATION OF LIABILITY IN THE AGREEMENT SHALL BE INCORPORATED BY REFERENCE WITH THE SAME FORCE AND EFFECT AS THOUGH FULLY SET FORTH HEREIN.
                            </p>
                            <br/>
                            <p>
                                WITH RESPECT TO THE USERS ACCESSING THE PLATFORM/WEBSITE BUT NOT SUBSCRIBED TO THE SERVICES, OUR TOTAL AGGREGATE LIABILITY UNDER THESE TERMS OF USE SHALL NOT EXCEED INDIAN RUPEES ONE THOUSAND ONLY.
                            </p>
                            <br/>
                            <p>
                                WE SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE WHICH MAY BE INCURRED BY YOU AS A RESULT OF: ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY, OR EXISTENCE OF ANY HYPERLINKED WEBSITE, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND SUCH HYPERLINKED WEBSITE WHOSE HYPERLINK APPEARS ON THE PLATFORM; ANY CHANGES WHICH WE MAY MAKE TO THE SERVICES, OR FOR ANY PERMANENT OR TEMPORARY CESSATION IN THE PROVISION OF THE SERVICES (OR ANY FEATURES WITHIN THE SERVICES); THE DELETION OF, CORRUPTION OF, OR FAILURE TO STORE, ANY CONTENT AND OTHER COMMUNICATIONS DATA MAINTAINED OR TRANSMITTED BY OR THROUGH YOUR USE OF THE SERVICES; YOUR FAILURE TO PROVIDE US WITH ACCURATE ACCOUNT INFORMATION; OR YOUR FAILURE TO KEEP YOUR PASSWORD OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL.
                            </p>
                            <br/>
                            <p>
                                YOU AGREE THAT YOUR USE OF OUR SERVICES IS VOLUNTARY AND WE HAVE NO LIABILITY TO YOU FOR ANY LOSS OF PROFIT, LOSS OF BUSINESS, LOSS OF GOODWILL OR BUSINESS REPUTATION, BUSINESS INTERRUPTION, OR LOSS OF BUSINESS OPPORTUNITY.
                            </p>
                            <br/>
                            <p>
                                WE WILL NOT BE LIABLE FOR DAMAGE THAT YOU COULD HAVE AVOIDED BY FOLLOWING OUR ADVICE TO APPLY AN UPDATE OFFERED TO YOU FREE OF CHARGE OR FOR DAMAGE THAT WAS CAUSED BY YOU FAILING TO CORRECTLY FOLLOW INSTALLATION INSTRUCTIONS OR TO HAVE IN PLACE THE MINIMUM SYSTEM REQUIREMENTS ADVISED BY US.
                            </p>
                            <br/>
                            <p>
                                YOU ARE RESPONSIBLE FOR ANY MOBILE CHARGES THAT MAY APPLY TO YOUR USE OF OUR SERVICE, INCLUDING TEXT MESSAGING AND DATA CHARGES.
                            </p>
                            <br/>
                            <p>
                                TO THE FULLEST EXTENT PERMITTED BY LAW, ANY DISPUTE YOU HAVE WITH ANY THIRD PARTY ARISING OUT OF YOUR USE OF THE SERVICES, INCLUDING, BY WAY OF EXAMPLE AND NOT LIMITATION, ANY CARRIER, COPYRIGHT OWNER OR OTHER USER, IS DIRECTLY BETWEEN YOU AND SUCH THIRD PARTY, AND YOU IRREVOCABLY RELEASE US AND OUR AFFILIATES FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES.
                            </p>
                            <br/>

                            <p>
                                <strong>14. INDEMNITY</strong>
                            </p>
                            <br/>
                            <p>
                                You hereby indemnify, defend, and hold Us, Our affiliates, licensors, distributors, agents, representatives and other authorized users, harmless from and against any and all losses, damages, liabilities and costs arising from or in connection with a) use of the Platform; b) the Your breach of any terms, obligations, representations and warranties under this Terms of Use; c) any claim that the provision or use of the Services infringes any third party rights; d) breach of applicable laws; and  (e) any claim arising from or relating to any User Content.
                            </p>
                            <br/>
                            <p>
                                Nothing in these Terms of Use shall exclude or limit Our liability for any liability which cannot be excluded or limited under applicable laws in force. Your statutory rights as a User are not affected by this Terms of Use.
                            </p>
                            <br/>
                            <p>
                                We also provide You Frequently Asked Question (FAQ) on the Platform where We shall address certain common questions that You as a User shall have while accessing the Platform and using Our Services.
                            </p>
                            <br/>

                            <p>
                                <strong>15. GRIEVANCE REDRESSAL MECHANISM</strong>
                            </p>
                            <br/>
                            <p>
                                Any complaints, abuse, or concerns with regards to the use, processing, and disclosure of information provided by You or breach of these Terms of Use or any applicable law should immediately be informed to the designated Grievance Officer at support@azoapp.tech
                            </p>
                            <br/>

                            <p>
                                <strong>16. FORCE MAJEURE</strong>
                            </p>
                            <br/>
                            <p>
                                We shall be relieved of all Our responsibilities, if any, in the event of failure of performance resulting directly or indirectly from an act of force majeure or causes beyond our reasonable control including, without limitation, acts of god, war, equipment and technical failures, electrical power failures or fluctuations, strikes, labour disputes, riots, civil disturbances, shortages of labour or materials, epidemics, pandemics, lockdown (state-wise or nation-wide), natural disasters, orders of domestic or foreign courts or tribunals, non-performance of third parties, or any reasons beyond Our reasonable control. You further acknowledge and agree that We are not responsible or liable for (a) any incompatibility between the Platform and any other website, service, software, or hardware or (b) any delays or failures You may experience with any transmissions or transactions relating to the Platform in an accurate or timely manner.
                            </p>
                            <br/>
                            <p>
                                <strong>17. GENERAL</strong>
                            </p>
                            <br/>
                            <p>
                                All notices shall be given to Us via email, or to You at either the email or postal address You provide.
                            </p>
                            <br/>
                            <p>
                                Any waiver of Our rights or remedy under these Terms of Use shall only be effective if it is in writing, executed by Our duly authorized representative, and shall be applicable only to the circumstances for which it is given. Our failure to exercise or enforce any right or remedy under these Terms of Use shall not operate as a waiver of such right or remedy, nor shall it prevent any future exercise or enforcement of such right or remedy. No single or partial exercise of any right or remedy shall preclude or restrict the further exercise of any such right, or remedy, or other rights or remedies.
                            </p>
                            <br/>
                            <p>
                                These Terms of Use, together with the Agreement, and Our Privacy Policies incorporated herein by reference, constitute the entire agreement between the parties with respect to the subject matter.
                            </p>
                            <br/>
                            <p>
                                The clause titles in these Terms of Use are for convenience only and have no legal or contractual effect. The words “including” and “includes” mean “including without limitation”.
                            </p>
                            <br/>
                            <p>
                                The provision(s) of these Terms of Use shall be sought to be harmoniously interpreted with each other, as well as applicable Laws (including the applicable laws based on the jurisdiction of the User’s) and upheld to the fullest extent permissible under applicable Laws. Further, the provisions contained in these Terms of Use shall be enforceable independently of each other, and their validity shall not be affected if any other provision(s) are held to be invalid. If any provision(s) of these Terms of Use is, for any reason, held to be invalid or unenforceable, the other provisions of these Terms of Use will be unimpaired (to the maximum extent permissible), and the invalid or unenforceable provision(s) will be deemed modified so that they are valid and enforceable to the maximum extent permitted by applicable Laws. Further, if any of those provision(s) are void but would be valid if some parts of the provision(s) were deleted, the provision(s) in question shall apply with such modification as may be necessary to make them valid.
                            </p>
                            <br/>
                            <p>
                                These Terms of Use and any dispute or claim arising out of or in connection with their subject matter or formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with the laws prevalent in India. You agree that the courts of Gurugram, Haryana, India shall have exclusive jurisdiction to settle any dispute, or claim, arising out of, or in relation to these Terms of Use.
                            </p>
                            <br/>
                            <p>
                                Last Updated on: 07-Sep-2023
                            </p>
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </>
    );
}
